from selenium.webdriver.common.by import By

LOGIN_LOCATOR = (By.CSS_SELECTOR, "div[class^='responseHead-module-button']")
EMAIL_LOCATOR = (By.NAME, "email")
PASSWORD_LOCATOR = (By.NAME, "password")
AUTH_LOCATOR = (By.CSS_SELECTOR, "div[class^='authForm-module-button']")
USER_ICON_LOCATOR = (By.CSS_SELECTOR, "div[class^='right-module-rightButton']")
LOGOUT_LOCATOR = (By.CSS_SELECTOR, "a[href='/logout']")
SPINNER_LOCATOR = (By.CSS_SELECTOR, "div[class^='spinner']")
PROFILE_LOCATOR = (By.CSS_SELECTOR, "a[href='/profile']")
FIO_LOCATOR = (By.XPATH, "//div[@data-name='fio']/div/input")
PHONE_LOCATOR = (By.XPATH, "//div[@data-name='phone']/div/input")
SUBMIT_LOCATOR = (By.CSS_SELECTOR, "button[class='button button_submit']")
SEGMENTS_LOCATOR = (By.CSS_SELECTOR, "a[href='/segments']")
BILLING_LOCATOR = (By.CSS_SELECTOR, "a[href='/billing']")